[package]
name = "bento-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
bento-core = { path = "../bento-core" }
async-trait = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
indexmap = { workspace = true }
which = "7"
