//! NSIS (Nullsoft Scriptable Install System) script generator.
//!
//! Generates a .nsi script from the compiled manifest, then invokes
//! `makensis` to produce a self-extracting Windows installer (.exe).
//!
//! The installer:
//! - Installs per-user to %LOCALAPPDATA%\Programs\<AppName> (no admin needed)
//! - Copies shell, supervisor, runtime-assets, and app bundle
//! - Creates a Start Menu shortcut
//! - Registers in Add/Remove Programs (HKCU)
//! - Launches the app after install
//! - Provides an uninstaller with "remove data" option
//!
//! See docs/decisions.md ADR-008 for rationale.

use std::path::{Path, PathBuf};

use craterun_bundle::manifest::compiled_manifest::CompiledManifest;

pub struct NsisInstaller {
    manifest: CompiledManifest,
    bundle_dir: PathBuf,
    output_dir: PathBuf,
}

/// Paths to binaries that the installer must embed.
/// These are built artifacts from the workspace.
pub struct InstallerBinaries {
    pub shell_exe: PathBuf,
    pub supervisor_exe: PathBuf,
}

impl NsisInstaller {
    pub fn new(manifest: CompiledManifest, bundle_dir: PathBuf, output_dir: PathBuf) -> Self {
        Self {
            manifest,
            bundle_dir,
            output_dir,
        }
    }

    /// Generate the NSIS script and write it to the output directory.
    pub fn generate_script(&self, binaries: &InstallerBinaries) -> anyhow::Result<PathBuf> {
        std::fs::create_dir_all(&self.output_dir)?;
        let script_path = self.output_dir.join("installer.nsi");
        let script = self.render_script(binaries);
        std::fs::write(&script_path, &script)?;
        Ok(script_path)
    }

    /// Invoke makensis to compile the .nsi script into a setup .exe.
    pub fn compile(&self, script_path: &Path) -> anyhow::Result<PathBuf> {
        let output_exe = self.output_dir.join(format!(
            "{}Setup.exe",
            self.manifest.app.name.replace(' ', "")
        ));

        let status = std::process::Command::new("makensis")
            .arg(script_path)
            .status();

        match status {
            Ok(s) if s.success() => Ok(output_exe),
            Ok(s) => anyhow::bail!("makensis exited with code {}", s),
            Err(e) => {
                if e.kind() == std::io::ErrorKind::NotFound {
                    anyhow::bail!(
                        "makensis not found. Install NSIS from https://nsis.sourceforge.io \
                         or add it to PATH. The .nsi script has been generated at {}",
                        script_path.display()
                    );
                }
                anyhow::bail!("failed to run makensis: {}", e);
            }
        }
    }

    fn render_script(&self, binaries: &InstallerBinaries) -> String {
        let app_name = &self.manifest.app.name;
        let app_id = &self.manifest.app.id;
        let app_version = &self.manifest.app.version;
        let exe_name = format!("{}Setup.exe", app_name.replace(' ', ""));
        let app_exe = format!("{}.exe", app_name.replace(' ', ""));

        // NSIS requires absolute backslash paths
        let abs = |p: &std::path::Path| -> String {
            std::fs::canonicalize(p)
                .unwrap_or_else(|_| p.to_path_buf())
                .to_string_lossy()
                .replace('/', "\\")
                // Remove \\?\ prefix that canonicalize adds on Windows
                .trim_start_matches(r"\\?\")
                .to_string()
        };
        let shell_exe = abs(&binaries.shell_exe);
        let supervisor_exe = abs(&binaries.supervisor_exe);
        let bundle_dir = abs(&self.bundle_dir);
        let output_dir = abs(&self.output_dir);

        format!(
            r#";; CrateRun-generated NSIS installer for {app_name}
;; DO NOT EDIT — regenerated by `craterun package`

!include "MUI2.nsh"

Name "{app_name}"
OutFile "{output_dir}\{exe_name}"
Unicode True

;; Per-user install — no admin elevation needed
RequestExecutionLevel user
InstallDir "$LOCALAPPDATA\Programs\{app_name}"

;; Installer UI
!define MUI_ABORTWARNING

;; Pages: minimal consumer flow (install confirmation + progress)
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
    SetOutPath "$INSTDIR"

    ;; App shell and supervisor binaries
    File "/oname={app_exe}" "{shell_exe}"
    File "/oname={app_id}-supervisor.exe" "{supervisor_exe}"

    ;; App bundle directory (manifest, images, assets, shell config)
    SetOutPath "$INSTDIR\bundle"
    File /r "{bundle_dir}\*.*"

    ;; Create data directory for runtime state
    CreateDirectory "$LOCALAPPDATA\CrateRun\Apps\{app_id}"
    CreateDirectory "$LOCALAPPDATA\CrateRun\Apps\{app_id}\config"
    CreateDirectory "$LOCALAPPDATA\CrateRun\Apps\{app_id}\logs"

    ;; Start Menu shortcut
    CreateDirectory "$SMPROGRAMS\{app_name}"
    CreateShortcut "$SMPROGRAMS\{app_name}\{app_name}.lnk" "$INSTDIR\{app_exe}"
    CreateShortcut "$SMPROGRAMS\{app_name}\Uninstall.lnk" "$INSTDIR\uninstall.exe"

    ;; Register uninstaller in Add/Remove Programs (per-user)
    WriteUninstaller "$INSTDIR\uninstall.exe"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}" \
        "DisplayName" "{app_name}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}" \
        "DisplayVersion" "{app_version}"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}" \
        "UninstallString" "$\"$INSTDIR\uninstall.exe$\""
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}" \
        "InstallLocation" "$INSTDIR"
    WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}" \
        "Publisher" "CrateRun"
    WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}" \
        "NoModify" 1
    WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}" \
        "NoRepair" 1

SectionEnd

;; Launch app after install
Function .onInstSuccess
    Exec "$INSTDIR\{app_exe}"
FunctionEnd

;; Uninstaller
Section "Uninstall"
    ;; Remove app files
    RMDir /r "$INSTDIR\bundle"
    Delete "$INSTDIR\{app_exe}"
    Delete "$INSTDIR\{app_id}-supervisor.exe"
    Delete "$INSTDIR\uninstall.exe"
    RMDir "$INSTDIR"

    ;; Remove Start Menu shortcuts
    Delete "$SMPROGRAMS\{app_name}\{app_name}.lnk"
    Delete "$SMPROGRAMS\{app_name}\Uninstall.lnk"
    RMDir "$SMPROGRAMS\{app_name}"

    ;; Remove registry entries
    DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\{app_id}"

    ;; Prompt user about app data
    MessageBox MB_YESNO "Remove app data (databases, settings)? Click No to keep your data." \
        /SD IDNO IDYES remove_data IDNO skip_data
    remove_data:
        RMDir /r "$LOCALAPPDATA\CrateRun\Apps\{app_id}"
    skip_data:

SectionEnd
"#,
            app_name = app_name,
            app_id = app_id,
            app_version = app_version,
            exe_name = exe_name,
            app_exe = app_exe,
            shell_exe = shell_exe,
            supervisor_exe = supervisor_exe,
            bundle_dir = bundle_dir,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use craterun_bundle::manifest::compiled_manifest::*;
    use indexmap::IndexMap;
    use craterun_core::types::*;

    fn sample_manifest() -> CompiledManifest {
        CompiledManifest {
            schema_version: "0.1".into(),
            app: CompiledAppInfo {
                id: "com.example.photobooth".into(),
                name: "PhotoBooth Local".into(),
                version: "1.0.0".into(),
            },
            runtime: RuntimeTarget {
                target: "windows-x64".into(),
                architecture: "linux/amd64".into(),
            },
            services: vec![],
            routes: vec![],
            health: CompiledHealth {
                ready: CompiledHealthCheck {
                    service: "api".into(),
                    path: "/health".into(),
                    timeout_seconds: 120,
                },
            },
            volumes: IndexMap::new(),
            window: CompiledWindow {
                title: "PhotoBooth Local".into(),
                width: 1200,
                height: 800,
                entry: "/".into(),
            },
            lifecycle: CompiledLifecycle {
                on_window_open: LifecycleAction::StartServices,
                on_window_close: LifecycleAction::StopServices,
            },
            install: CompiledInstall {
                mode: InstallMode::Consumer,
                ask_questions: false,
            },
        }
    }

    #[test]
    fn nsis_script_contains_required_sections() {
        let manifest = sample_manifest();
        let installer = NsisInstaller::new(
            manifest,
            PathBuf::from("C:\\build\\bundle"),
            PathBuf::from("C:\\build\\dist"),
        );
        let binaries = InstallerBinaries {
            shell_exe: PathBuf::from("C:\\build\\shell.exe"),
            supervisor_exe: PathBuf::from("C:\\build\\supervisor.exe"),
        };

        let script = installer.render_script(&binaries);

        assert!(script.contains("PhotoBooth Local"), "missing app name");
        assert!(script.contains("com.example.photobooth"), "missing app id");
        assert!(script.contains("RequestExecutionLevel user"), "must be per-user");
        assert!(script.contains("WriteUninstaller"), "must create uninstaller");
        assert!(script.contains("CreateShortcut"), "must create Start Menu shortcut");
        assert!(script.contains("HKCU"), "must use per-user registry");
        assert!(script.contains("WriteRegStr"), "must register in Add/Remove Programs");
        assert!(script.contains("Section \"Uninstall\""), "must have uninstall section");
        assert!(script.contains("Remove app data"), "must prompt about data on uninstall");
    }

    #[test]
    fn installer_exe_name_strips_spaces() {
        let manifest = sample_manifest();
        let installer = NsisInstaller::new(
            manifest,
            PathBuf::from("C:\\build\\bundle"),
            PathBuf::from("C:\\build\\dist"),
        );
        let binaries = InstallerBinaries {
            shell_exe: PathBuf::from("shell.exe"),
            supervisor_exe: PathBuf::from("supervisor.exe"),
        };

        let script = installer.render_script(&binaries);
        assert!(script.contains("PhotoBoothLocalSetup.exe"));
    }
}
